config/routes.rb
Rails.application.routes.draw do
  # get 'projects/show'
  # post 'projects/create' => 'projects#create'
  # get 'projects/new'
  # get 'projects/update'
  # get 'projects/delete'
 
  resources :projects
  
  get 'sessions/new'
  get '/login' => 'sessions#new'
  get '/dashboard' => 'sessions#dashboard'
  post '/login' => 'sessions#login'
  get '/logout' => 'sessions#logout'

  get '/signup' => 'users#signup'
  post '/users' => 'users#create'  
  get 'users/edit' => "users#edit"
  patch 'users/update' => "users#update"
  get 'users/destroy'
  get 'users/admin'
  get '/project/:id' => 'projects#single'

  root "projects#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  # default_scope -> { order (created_at: :desc)}
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true, length: {minimum: 10, maximum: 50}
  validates :description, presence: true, length: {minimum: 1, maximum: 20}
  validates :img, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :projects, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
  
    def authorize
      redirect_to '/login' unless current_user
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # before_action :logged_in_user, only: [:create, :destroy]
  def show
     @projects = Project.all
     
  end
  
  def single 
    @project = Project.find(params[:id])  
     
  end

  def create      
    @project = current_user.projects.build(project_params)  
    if @project.save      
      redirect_to '/'
    else
      flash[:errors] = @project.errors.full_messages      
      redirect_to '/projects/new'
    end
  end

  def edit
    @project = Project.find(params[:id])  
  end

  def update
    @project = Project.find(params[:id])     
    @project.update(project_params)
    redirect_to '/dashboard'
  end

  def destroy    
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to '/dashboard'
  end
  private
    def project_params
      params.require(:project).permit(:content, :title, :img, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

  def dashboard
    @users = User.all
    @user = User.find(session[:user_id])
    @projects = Project.where(["user_id = ?",  @user[:id]])
    
  end


  def login
    @user = User.find_by(email: permit[:email])   
    if @user && @user.authenticate(permit[:password])     
      session[:user_id] = @user.id
      redirect_to '/'
    else      
       flash.now[:errors] = 'Invalid Email or password'
       render 'new'     

    end
  end
  def destroy
    render plain: params.inspect
    # @project = Project.find()
    # @user.destroy
    # redirect_to users_path
    
  end
  def logout
    session[:user_id] = nil
    redirect_to '/login'
  end

  def permit
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
    @user = User.new
  end
 
  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:errors] = @user.errors.full_messages      
      redirect_to '/signup'
    end
  end
  def show
    @user = User.find(params[:id])
  end

   def edit
    @user = User.find(params[:format])
  end

   def update
    @user = User.find(params[:format])    
    @user.update(params.require(:user).permit(:name, :email, :password))
    redirect_to '/dashboard'
  end

  def destroy   
    @user = User.find(params[:format])
    if current_user.admin
      @user.destroy
      redirect_to '/dashboard'
    elsif current_user.email == @user[:email]     
      @user.destroy
      session[:user_id] = nil   
      redirect_to '/login'   
    else
      flash.now[:errors] = 'You dont have admin priviledges'
      redirect_to '/dashboard'
    end   
        
  end

  def admin
    @user = User.find(params[:format])
    if @user.admin == false || @user.admin == nil
      @user.update_attribute(:admin, true)
      redirect_to '/dashboard'
    else
      @user.update_attribute(:admin, false)
      redirect_to '/dashboard'
    end
    
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    </head>  

  <body>
  
  <div class="site-header d-flex flex-md-row align-items-center p-3 px-md-4  border-bottom box-shadow">
      <a class="my-0 mr-md-auto font-weight-normal">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mx-auto"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
      </a>
        <nav class="my-2 my-md-0 mr-md-3">
         <a class="py-2 text-dark mr-3" <%= link_to  "Home", '/' %></a>

        <% if current_user %>
             <%= link_to "Dashboard", '/dashboard', class: "py-2 text-dark mr-3" %>  
            Welcome <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
          <% else %>          
          <%= link_to "Login", '/login', class: "py-2 text-dark mr-3" %> 
          <%= link_to "SIGN UP", '/signup', class: "btn btn-outline-primary mr-3" %>
          <% end %> 
       
      </nav>
      
    </div>    

  <div class="container mt-5 mb-5">
    <%= yield %>
  </div>
  </body>
</html>

app/views/projects/delete.html.erb
<h1>Projects#delete</h1>
<p>Find me in app/views/projects/delete.html.erb</p>

app/views/projects/edit.html.erb
  <h1 class="text-center mb-3  mt-3">New Project</h1>
<div class="container card  pt-3">
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p class="alert alert-danger" role="alert"> <%= error %></p>
    <%end%>
<%end%>
<div class="card-body">
 <%= form_for(@project) do |f| %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :title, "Title", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :img, "Img Url", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.text_field :img, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :description, "Description", class: "col-md-4 control-label mt-3" %>
        <div class="col-md-12">
          <%= f.text_area :description, placeholder: "Project description..", class: "form-control" %>
        </div>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :content, "Content", class: "col-md-4 control-label mt-3" %>
        <div class="col-md-12">
          <%= f.text_area :content, placeholder: "Full content..", class: "form-control" %>
        </div>
      </div>
      
    </div>
      
     <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
     
     </div>

 <% end %> 




</div>
</div>

app/views/projects/new.html.erb
  <h1 class="text-center mb-3  mt-3">New Project</h1>
<div class="container card  pt-3">
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p class="alert alert-danger" role="alert"> <%= error %></p>
    <%end%>
<%end%>
<div class="card-body">
 <%= form_for(:project, url: '/projects') do |f| %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :title, "Title", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :img, "Img Url", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.text_field :img, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :description, "Description", class: "col-md-4 control-label mt-3" %>
        <div class="col-md-12">
          <%= f.text_area :description, placeholder: "Project description..", class: "form-control" %>
        </div>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :content, "Content", class: "col-md-4 control-label mt-3" %>
        <div class="col-md-12">
          <%= f.text_area :content, placeholder: "Full content..", class: "form-control" %>
        </div>
      </div>
      
    </div>
      
     <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
     
     </div>

 <% end %> 




</div>
</div>

app/views/projects/show.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">Let's manage all your projects</h1>
          <p class="lead my-3 wow fadeInLeft animated">From simple to large projects, our systems are scalable and flexible and are designed to manage projects, MyBasecamp gives you a place to share things company-wide, within a team, or for a specific project.</p>
           <% if current_user %>
              <%= link_to "New Project", '/projects/new', class: "btn btn-outline-secondary" %>
          <% else %>
              <%= link_to "New Project", '/login', class: "btn btn-outline-secondary" %>
          <% end %>
            
        </div>
</div>


<h3 class="mb-5">
   <a class="text-dark mb-4">Project Gallery</a><br>                
  </h3>
<div class="row mb-2 wow fadeInRight animated">
    <% @projects.each do |p| %>
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              
              <h3 class="mb-0">
                <a class="text-dark mb-4"><%= p.title %></a><br>                
              </h3>
              <div class="mb-1 text-muted pt-2">
              <%= p.created_at.strftime(" %B %d, %Y") %> 
              <strong class="d-inline-block mb-2 text-primary"> by <%= User.find(p.user_id).name %> </strong></div>
              <p class="card-text mb-auto"><%= p.description %></p>
              
               <%= link_to "Continue reading", 'project/' + p.id.to_s %>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" 
            alt="Thumbnail [200x250]" style="width: 200px; height: 250px;" src="<%= p.img %>" data-holder-rendered="true">
          </div>
        </div>
    <% end %>
  </div>

app/views/projects/single.html.erb
 <div class="blog-post">
            <h2 class="blog-post-title"><%= @project.title %></h2>
            <p class="blog-post-meta"><%= @project.created_at.strftime("%m/%d/%Y") %> by Mr<a href="#"><%= @project.user_id %></a></p>

            <p><%= @project.description %></p>
            <hr>
            <p><%= @project.content %></p>
           
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
  <h1 class="text-center mb-3  mt-3">Edit Profile</h1>
<div class="container card  pt-3">
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p class="alert alert-danger" role="alert"> <%= error %></p>
    <%end%>
<%end%>
<div class="card-body">
 <%= form_for(@user, url: users_update_path(@user)) do |f| %>
      <div class="form-group">
        <%= f.label :name, "Username", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, "Email", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, "Password", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>     
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm Password", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>     
     <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
     
     </div>

 <% end %> 




</div>
</div>

app/views/users/signup.html.erb
  <h1 class="text-center mb-3  mt-3">SignUp</h1>
<div class="container card  pt-3">
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p class="alert alert-danger" role="alert"> <%= error %></p>
    <%end%>
<%end%>
<div class="card-body">
 <%= form_for User.new do |f| %>
      <div class="form-group">
        <%= f.label :name, "Username", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, "Email", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, "Password", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>     
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm Password", class: "col-md-4 control-label" %>
        <div class="col-md-12">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>     
     <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
     
     </div>

 <% end %> 




</div>
</div>

app/views/users/update.html.erb
<h1> </h1>
<p>Find me in app/views/users/update.html.erb</p>